#server:
#  port: 8088
#emp的配置数据
emp:
  lastName: 张三
  age: 28
  salary: 20000
  boss: true
  birthday: 1888/08/08
  map:
    key1: value1
    key2: value2
  list:
    - one
    - two
    - three
  forte:
    name: java
    time: 8